CREATE TABLE PARKING_PLACE (
 PLACE_NUMBER INT NOT NULL,
 BOOKING_DETAIL_ID INT NOT NULL,
 CAR_ID INT NOT NULL,
 PRIMARY KEY(PLACE_NUMBER),
 FOREIGN KEY(BOOKING_DETAIL_ID) references BOOKING_DETAIL,
 FOREIGN KEY(CAR_ID) references CAR
);